### ISSUE TITLE
update graph

### ISSUE THREAD

**Issue by 2075** [gamedaoco/gamedao-graph#1]
### MACHINE 1
- full subzero **alphaville** node (archive.gamedao.co)

- [ ] remove unnecessary services
- [ ] assign a domain
- [ ] create or update archiver node for alphaville
- [ ] add separate nginx / letsencrypt, e.g. jwilder standard docker or other proven setup

### MACHINE 2
- public graph (graph.gamedao.co)
- indexer ( indexer.gamedao.co) 
- squid ( squid.gamedao.co) 

- [ ] create new aws machine 
- [ ] create dockerfile with
- archiver
- squid
- graph with subscriptions
- [ ] add separate nginx / letsencrypt, e.g. jwilder standard docker or other proven setup
- [ ] expose graph to public
- [ ] create three docker-compose after successful test (low prio)

## 3. update zero / gamedao schemas ( @vasylenko-yevhen )
- [ ] review existing schema and complete this list 
- [ ] add relevant orml ( currencies? )
- [ ] add proposals
- [ ] add signal
- [ ] add tangram ( tbd )
- [ ] add uniques

### MACHINE 3 (kusama.gamedao.co)

- [ ] add kusama archiver ( low prio )
- [ ] add separate nginx / letsencrypt, e.g. jwilder standard docker or other proven setup

- [ ] add rmrk assets from kusama
- [ ] reindex if neccessary

**Comment by Persqual** [comment]
@2075 Quick question to #1:
Do you mean "alphaville" or "beeblebrox"? Will we add a Graph to our beta.gamedao.co app or did I misunderstood smth. between those two nodes? Thought the alphaville is beta and the beeblebrox was the chain upgrade.

**Comment by 5-mark** [comment]
@Persqual alphaville is the new upgraded chain which you can find here: 
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Falphaville.zero.io#/

beeblebrox is the chain you can find here:
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fbeeblebrox.zero.io%2Fnode#/

So far alphaville is connected to beta and beeblebrox to haiku - but we want the network connector to be able to switch between both networks (https://github.com/gamedaoco/gamedao-haiku/issues/166)


So to conclude: the alphaville is alphaville and beeblebrox is beeblebrox and haiku should be able to connect both. 
The old frontend (beta) will be closed somewhen soon (or we rename haiku to beta...didnt make up my mind yet).

**Comment by 5-mark** [comment]
deprecated:
```
we decided to use another approach, which does not include most of the items listed in the task.
We decided to setup additional Hasura, which will provide subscriptions until subsquid did not implement them natively.
```
